exec: MachManager/removables/management.o MachManager/removables/ui.o MachManager/removables/uirelated.o \
      ../Sprint2/USAC01/files/usac01.o ../Sprint2/USAC02/files/usac02.o ../Sprint2/USAC03/files/usac03.o ../Sprint2/USAC04/files/usac04.o \
      ../Sprint2/USAC05/files/usac05.o ../Sprint2/USAC06/files/usac06.o ../Sprint2/USAC07/files/usac07.o ../Sprint2/USAC08/files/usac08.o \
      ../Sprint2/USAC09/files/usac09.o ../Sprint2/USAC10/files/usac10.o \
      MachManager/removables/machineRelated.o  
	gcc MachManager/removables/management.o MachManager/removables/ui.o MachManager/removables/uirelated.o \
	    ../Sprint2/USAC01/files/usac01.o ../Sprint2/USAC02/files/usac02.o ../Sprint2/USAC03/files/usac03.o ../Sprint2/USAC04/files/usac04.o \
	    ../Sprint2/USAC05/files/usac05.o ../Sprint2/USAC06/files/usac06.o ../Sprint2/USAC07/files/usac07.o ../Sprint2/USAC08/files/usac08.o \
	    ../Sprint2/USAC09/files/usac09.o ../Sprint2/USAC10/files/usac10.o \
	    MachManager/removables/machineRelated.o -o MachManager/removables/exec

MachManager/removables/management.o: MachManager/management.c \
      ../Sprint2/USAC01/files/usac01.o ../Sprint2/USAC02/files/usac02.o ../Sprint2/USAC03/files/usac03.o ../Sprint2/USAC04/files/usac04.o \
      ../Sprint2/USAC05/files/usac05.o ../Sprint2/USAC06/files/usac06.o ../Sprint2/USAC07/files/usac07.o ../Sprint2/USAC08/files/usac08.o \
      ../Sprint2/USAC09/files/usac09.o ../Sprint2/USAC10/files/usac10.o \
      MachManager/removables/machineRelated.o  
	mkdir -p MachManager/removables
	gcc -g -Wall -Wextra -fanalyzer -c MachManager/management.c -o MachManager/removables/management.o


MachManager/removables/ui.o: UI/ui.c \
      ../Sprint2/USAC01/files/usac01.o ../Sprint2/USAC02/files/usac02.o ../Sprint2/USAC03/files/usac03.o ../Sprint2/USAC04/files/usac04.o \
      ../Sprint2/USAC05/files/usac05.o ../Sprint2/USAC06/files/usac06.o ../Sprint2/USAC07/files/usac07.o ../Sprint2/USAC08/files/usac08.o \
      ../Sprint2/USAC09/files/usac09.o ../Sprint2/USAC10/files/usac10.o \
      MachManager/removables/machineRelated.o  
	mkdir -p MachManager/removables
	gcc -g -Wall -Wextra -fanalyzer -c UI/ui.c -o MachManager/removables/ui.o


MachManager/removables/uirelated.o: UI/UIrelated.c \
      ../Sprint2/USAC01/files/usac01.o ../Sprint2/USAC02/files/usac02.o ../Sprint2/USAC03/files/usac03.o ../Sprint2/USAC04/files/usac04.o \
      ../Sprint2/USAC05/files/usac05.o ../Sprint2/USAC06/files/usac06.o ../Sprint2/USAC07/files/usac07.o ../Sprint2/USAC08/files/usac08.o \
      ../Sprint2/USAC09/files/usac09.o ../Sprint2/USAC10/files/usac10.o \
      MachManager/removables/machineRelated.o 
	mkdir -p MachManager/removables
	gcc -g -Wall -Wextra -fanalyzer -c UI/UIrelated.c -o MachManager/removables/uirelated.o

../Sprint2/USAC01/files/usac01.o: ../Sprint2/USAC01/src/usac01.s
	mkdir -p ../Sprint2/USAC01/files
	gcc -g -Wall -Wextra -fanalyzer -c ../Sprint2/USAC01/src/usac01.s -o ../Sprint2/USAC01/files/usac01.o

../Sprint2/USAC02/files/usac02.o: ../Sprint2/USAC02/src/usac02.s
	mkdir -p ../Sprint2/USAC02/files
	gcc -g -Wall -Wextra -fanalyzer -c ../Sprint2/USAC02/src/usac02.s -o ../Sprint2/USAC02/files/usac02.o

../Sprint2/USAC03/files/usac03.o: ../Sprint2/USAC03/src/usac03.s
	mkdir -p ../Sprint2/USAC03/files
	gcc -g -Wall -Wextra -fanalyzer -c ../Sprint2/USAC03/src/usac03.s -o ../Sprint2/USAC03/files/usac03.o

../Sprint2/USAC04/files/usac04.o: ../Sprint2/USAC04/src/usac04.s
	mkdir -p ../Sprint2/USAC04/files
	gcc -g -Wall -Wextra -fanalyzer -c ../Sprint2/USAC04/src/usac04.s -o ../Sprint2/USAC04/files/usac04.o

../Sprint2/USAC05/files/usac05.o: ../Sprint2/USAC05/src/usac05.s
	mkdir -p ../Sprint2/USAC05/files
	gcc -g -Wall -Wextra -fanalyzer -c ../Sprint2/USAC05/src/usac05.s -o ../Sprint2/USAC05/files/usac05.o

../Sprint2/USAC06/files/usac06.o: ../Sprint2/USAC06/src/usac06.s
	mkdir -p ../Sprint2/USAC06/files
	gcc -g -Wall -Wextra -fanalyzer -c ../Sprint2/USAC06/src/usac06.s -o ../Sprint2/USAC06/files/usac06.o

../Sprint2/USAC07/files/usac07.o: ../Sprint2/USAC07/src/usac07.s
	mkdir -p ../Sprint2/USAC07/files
	gcc -g -Wall -Wextra -fanalyzer -c ../Sprint2/USAC07/src/usac07.s -o ../Sprint2/USAC07/files/usac07.o

../Sprint2/USAC08/files/usac08.o: ../Sprint2/USAC08/src/usac08.s
	mkdir -p ../Sprint2/USAC08/files
	gcc -g -Wall -Wextra -fanalyzer -c ../Sprint2/USAC08/src/usac08.s -o ../Sprint2/USAC08/files/usac08.o

../Sprint2/USAC09/files/usac09.o: ../Sprint2/USAC09/src/usac09.s
	mkdir -p ../Sprint2/USAC09/files
	gcc -g -Wall -Wextra -fanalyzer -c ../Sprint2/USAC09/src/usac09.s -o ../Sprint2/USAC09/files/usac09.o

../Sprint2/USAC10/files/usac10.o: ../Sprint2/USAC10/src/usac10.s
	mkdir -p ../Sprint2/USAC10/files
	gcc -g -Wall -Wextra -fanalyzer -c ../Sprint2/USAC10/src/usac10.s -o ../Sprint2/USAC10/files/usac10.o

MachManager/removables/machineRelated.o: Machine/machineRelated.c
	mkdir -p MachManager/removables
	gcc -g -Wall -Wextra -fanalyzer -c Machine/machineRelated.c -o MachManager/removables/machineRelated.o

clean:
	rm -rf MachManager/removables

run: exec
	./MachManager/removables/exec